### PR TITLE
feat: stop decoding without error if EOF encountered during header read

### LINKED ISSUE #16: EOF in `next` should return the already parsed, valid structures
Due to [changes in the latest LTS and thus in v1.7.6](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.6.39&id=50c6c51972e9561b58bc814d5953e83c3159494e) the DMI sysfs file will EOF where previously it would continue on and be decoded without error. This currently leads to errors, for example at:

https://github.com/siderolabs/go-smbios/blob/c5267640be317efd9cbbe936ab78b2a49c757edf/smbios/internal/github.com/digitalocean/go-smbios/smbios/decoder.go#L134

which with Talos manifests as:

```
controller failed {"component": "controller-runtime", "controller": "hardware.SystemInfoController", "error": "failed to decode structures: next error: error reading header: EOF"}
```

which can lead to errors decrypting partitions encrypted in v1.7.5.

I think we can do [what Linux does in this case and be lenient](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/firmware/dmi_scan.c?h=v6.6.39&id=50c6c51972e9561b58bc814d5953e83c3159494e#n97) and [just return the structures we've already parsed instead of `nil` here](https://github.com/siderolabs/go-smbios/blob/c5267640be317efd9cbbe936ab78b2a49c757edf/smbios/internal/github.com/digitalocean/go-smbios/smbios/decoder.go#L81).

### PR DESCRIPTION
**Pull request by michaelbeaumont**
Linux v6.6.39 stops decoding with EOF in this situation but maintains the already decoded structures. See [/drivers/firmware/dmi_scan.c](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/firmware/dmi_scan.c?h=v6.6.39&id=50c6c51972e9561b58bc814d5953e83c3159494e#n97)

I included a test with the DMI I'm using.

Fixes https://github.com/siderolabs/go-smbios/issues/16

### CODE REVIEW

**Comment by smira** [comment]
I updated the code, brought back removed tests, and made it actually match Linux - to assume table done on any header short read.

**Review by frezbo — APPROVED** [review]

**Review by smira — APPROVED** [review]

**Comment by michaelbeaumont** [comment]
Ok, yeah I returned an empty header and relied on the existing behavior with zero value Header but probably better indeed to treat both "bad DMI" cases individually.

Thanks!

**Comment by smira** [comment]
> Ok, yeah I returned an empty header and relied on the existing behavior with zero value Header but probably better indeed to treat both "bad DMI" cases individually.

The problem was with `io.EOF` and `io.ErrUnexpectedEOF`, as it depends on whether there were 0 bytes or 1,2,3 bytes available.

Thank you for the change!

**Pull request merged**
